import{S as f,i as n}from"./assets/vendor-7659544d.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function m(o){const r="https://pixabay.com/api/",s="43043595-2b9ab8fff7b2b720f98fadc4f",a=new URLSearchParams({key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}),e=`${r}?${a}`;return fetch(e).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const c=document.querySelector(".gallery"),p=new f(".gallery a",{captionsData:"alt",captionDelay:250});p.refresh();function g(o){c.innerHTML="",o.length===0?(n.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),hideLoader()):(o.forEach(r=>{const s=`
      <li class="gallery-item">
        <a href="${r.largeImageURL}" class="gallery-link">
          <img src="${r.webformatURL}" alt="${r.tags}" class="gallery-img">
          <ul class="gallery-descript">
    <li class="gallery-descript__item"><p><span class="gallery-descript__span">Likes</span>${r.likes}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Views</span>${r.views}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Comments</span>${r.comments}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Downloads</span>${r.downloads}</p></li>
        </ul>
        </a>
      </li>
    `;c.insertAdjacentHTML("beforeend",s)}),p.refresh())}const d=document.querySelector(".search-form"),h=document.querySelector(".search-input"),u=document.querySelector(".loader");function y(){u.classList.remove("is-hidden")}function l(){u.classList.add("is-hidden")}l();d.addEventListener("submit",F);function F(o){o.preventDefault(),y();const r=h.value.trim();r!==""?m(r).then(s=>{console.log(s),g(s.hits),d.reset(),l()}).catch(s=>{console.log(s),n.error({message:"Failed to fetch images. Please try again later.",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),l()}):(n.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),l())}
//# sourceMappingURL=commonHelpers.js.map
