import{i as n}from"./assets/vendor-38388549.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function u(o){const r="https://pixabay.com/api/",s=new URLSearchParams({keys:"43043595-2b9ab8fff7b2b720f98fadc4f",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}),a=`${r}?${s}`;return fetch(a).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}const c=document.querySelector(".gallery");function f(o){c.innerHTML="",o.length===0?(n.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),l()):(o.forEach(r=>{const s=`
      <li class="gallery-item">
        <a href="${r.largeImageURL}" class="gallery-link">
          <img src="${r.webformatURL}" alt="${r.tags}" class="gallery-img">
          <ul class="gallery-descript">
    <li class="gallery-descript__item"><p><span class="gallery-descript__span">Likes</span>${r.likes}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Views</span>${r.views}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Comments</span>${r.comments}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Downloads</span>${r.downloads}</p></li>
        </ul>
        </a>
      </li>
    `;c.insertAdjacentHTML("beforeend",s)}),m.refresh())}const m=new SimpleLightbox(".gallery a",{captionsData:"alt",captionDelay:250}),p=document.querySelector(".search-form"),g=document.querySelector(".search-input"),d=document.querySelector(".loader");function h(){d.classList.remove("is-hidden")}function l(){d.classList.add("is-hidden")}l();p.addEventListener("submit",y);function y(o){o.preventDefault(),h();const r=g.value.trim();r!==""?u(r).then(s=>{f(s.hits),p.reset()}).catch(s=>{console.log(s),n.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),l()}):(n.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),l())}
//# sourceMappingURL=commonHelpers.js.map
