import{S as d,i}from"./assets/vendor-7659544d.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function u(o){const r="https://pixabay.com/api/",s="43043595-2b9ab8fff7b2b720f98fadc4f",a=new URLSearchParams({key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}),e=`${r}?${a}`;return fetch(e).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const n=document.querySelector(".gallery"),c=new d(".gallery a",{captionsData:"alt",captionDelay:250});c.refresh();function f(o){n.innerHTML="",o.length===0?(i.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),hideLoader()):(o.forEach(r=>{const s=`
      <li class="gallery-item">
        <a href="${r.largeImageURL}" class="gallery-link">
          <img src="${r.webformatURL}" alt="${r.tags}" class="gallery-img">
          <ul class="gallery-descript">
    <li class="gallery-descript__item"><p><span class="gallery-descript__span">Likes</span>${r.likes}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Views</span>${r.views}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Comments</span>${r.comments}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Downloads</span>${r.downloads}</p></li>
        </ul>
        </a>
      </li>
    `;n.insertAdjacentHTML("beforeend",s)}),c.refresh())}const p=document.querySelector(".search-form"),m=document.querySelector(".search-input");document.querySelector(".loader");hideLoader();p.addEventListener("submit",g);function g(o){o.preventDefault();const r=m.value.trim();r!==""?u(r).then(s=>{console.log(s),f(s.hits),p.reset()}).catch(s=>{console.log(s),i.error({message:"Failed to fetch images. Please try again later.",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),hideLoader()}):(i.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),hideLoader())}
//# sourceMappingURL=commonHelpers.js.map
